defaults: &defaults
  working_directory: ~/annuaire-api
  docker:
    - image: circleci/node:12

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/annuaire-api
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - test:
          requires:
            - install
