name: Node.js CI / Scalingo CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    # https://crontab.guru/#0_2_*_*_*
    - cron: "0 2 * * *"

env:
  SCALINGO_API_URL: api.osc-fr1.scalingo.com
  SCALINGO_APP: annuaire-etablissements-publics
  SOURCE_ARCHIVE: https://github.com/BaseAdresseNationale/annuaire-api/archive/master.tar.gz

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn lint
      - run: yarn test
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Trigger a deployment on scalingo
          shell: bash
          run: |
            curl -H "Accept: application/json" -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${{ secrets.SCALINGO_BEARER_TOKEN }}" \
              -X POST https://${{ SCALINGO_API_URL }}/v1/apps/${{ SCALINGO_APP }}/deployments -d \
              '{
                "deployment": {
                  "git_ref": "master",
                  "source_url": "${{ SOURCE_ARCHIVE }}"
                }
              }'
